import express from "express";
import path from "path";
import { createServer as createViteServer } from "vite";
import { GoogleGenAI } from "@google/genai";

const app = express();
const PORT = 3000;

app.use(express.json({ limit: "50mb" }));

// Initialize Gemini SDK with telemetry header
const ai = new GoogleGenAI({
  apiKey: process.env.GEMINI_API_KEY || "",
  httpOptions: {
    headers: {
      "User-Agent": "aistudio-build",
    },
  },
});

// System info
const ESELLERS_METADATA = {
  themeName: "E-sellers Pro",
  developer: "E-sellers",
  developerEmail: "info@e-sellers.net",
  version: "1.0.0",
  shopifyOS: "2.0",
};

// Healthcheck API
app.get("/api/health", (_req, res) => {
  res.json({ status: "ok", metadata: ESELLERS_METADATA });
});

// AI Generator API: Generate or Refactor Liquid Section
app.post("/api/gemini/generate-section", async (req, res) => {
  try {
    const { prompt, sectionType, existingCode, mode } = req.body;

    const systemInstruction = `You are a master Shopify Liquid & Storefront OS 2.0 developer building code for the "E-sellers Pro" theme (Developer: E-sellers, Email: info@e-sellers.net).
Generate highly performant, semantic, accessible, and valid Shopify Liquid OS 2.0 section code.
Each section MUST include:
1. Liquid template code with modern filters (e.g. image_url, render, | t, default).
2. Embedded CSS or inline Liquid styles wrapped in {% style %}...{% endstyle %} using clean CSS variables.
3. Embedded JavaScript if needed wrapped in {% javascript %}...{% endjavascript %}.
4. Valid JSON Schema wrapped in {% schema %}{...}{% endschema %} with:
   - "name", "tag": "section", "class", "settings" (with type, id, label, default)
   - "blocks" (if relevant for repetitive items like slides, features, badges)
   - "presets": [{ "name": "...", "category": "..." }]
5. Header comments identifying "Theme: E-sellers Pro | Developer: E-sellers (info@e-sellers.net)".

Return ONLY a JSON object with keys:
- "liquidCode": string (the complete .liquid section code)
- "sectionName": string (e.g. "e-sellers-hero-banner.liquid")
- "description": string
- "settingsCount": number
- "blocksCount": number`;

    const userPrompt = mode === "refactor"
      ? `Refactor the following code to adhere strictly to Shopify OS 2.0 best practices and E-sellers Pro theme standards:\n\n${existingCode}\n\nAdditional instructions: ${prompt}`
      : `Create a new Shopify OS 2.0 Liquid section for theme "E-sellers Pro". Section Type/Idea: ${sectionType || "Custom Section"}.\nInstructions: ${prompt}`;

    const response = await ai.models.generateContent({
      model: "gemini-3.6-flash",
      contents: userPrompt,
      config: {
        systemInstruction,
        responseMimeType: "application/json",
      },
    });

    const resultText = response.text || "{}";
    const data = JSON.parse(resultText);
    res.json({ success: true, data });
  } catch (error: any) {
    console.error("Error in generate-section:", error);
    res.status(500).json({ success: false, error: error.message || "Failed to generate Liquid section" });
  }
});

// AI Batch Compatibility Check & Snippet Repair API
app.post("/api/gemini/batch-compatibility-check", async (req, res) => {
  try {
    const { files, developerInfo } = req.body;

    const systemInstruction = `You are an expert Shopify OS 2.0 Theme Refactoring & Compatibility Engine for "E-sellers Pro" (Developer: ${developerInfo?.developer || 'E-sellers'}, Email: ${developerInfo?.email || 'info@e-sellers.net'}).
Analyze the provided batch of theme files (sections, snippets, layout, config) extracted from a third-party ZIP file.

Your tasks:
1. Identify any missing snippets or assets referenced in Liquid tags (e.g., {% render 'missing-snippet' %}).
2. Identify deprecated Liquid tags or non-standard theme settings that need refactoring.
3. Suggest necessary polyfills, theme-variables snippets, or structural updates to make the imported theme 100% compatible with E-sellers Pro.

Return ONLY a JSON object:
- "compatibilityScore": number (0 to 100)
- "filesProcessedCount": number
- "deprecatedTagsFound": string[]
- "missingSnippetsIdentified": string[]
- "autoGeneratedSnippets": Array<{ path: string; content: string; description: string }>
- "summaryReport": string`;

    const response = await ai.models.generateContent({
      model: "gemini-3.6-flash",
      contents: `Developer Branding: ${JSON.stringify(developerInfo || {})}\n\nTheme Files Summary:\n${JSON.stringify((files || []).slice(0, 30).map((f: any) => ({ path: f.path, length: f.content?.length || 0 })), null, 2)}`,
      config: {
        systemInstruction,
        responseMimeType: "application/json",
      },
    });

    const resultText = response.text || "{}";
    const data = JSON.parse(resultText);
    res.json({ success: true, data });
  } catch (error: any) {
    console.error("Error in batch-compatibility-check:", error);
    res.status(500).json({ success: false, error: error.message || "Failed to analyze batch compatibility" });
  }
});

// AI Cloner & Refactor API: Convert external theme section into E-sellers Pro format
app.post("/api/gemini/clone-refactor", async (req, res) => {
  try {
    const { sourceFileName, sourceLiquidCode, customizationNotes } = req.body;

    const systemInstruction = `You are a Shopify Theme Migration & Refactoring Specialist working on "E-sellers Pro" (Developer: E-sellers, Email: info@e-sellers.net).
Your job is to analyze an existing Shopify theme section (from third-party themes like Dawn, Impulse, Ella, Prestige, etc.) and clone/refactor it into a clean, standalone, highly optimized section for E-sellers Pro.

Requirements:
1. Standardize setting IDs and CSS class names with the "es-" prefix (e.g. es-section-header, es_padding_top).
2. Replace obsolete Liquid tags:
   - Replace 'include' with 'render'
   - Replace 'img_url' with 'image_url' and proper width/height parameters
   - Ensure responsive images use loading="lazy" or fetchpriority="high"
3. Clean up and optimize the JSON Schema {% schema %}: ensure valid JSON syntax, readable settings, and preset block configurations.
4. Add E-sellers Pro metadata header comments:
   {% comment %}
     Theme: E-sellers Pro
     Developer: E-sellers (info@e-sellers.net)
     Section: Cloned & Refactored from ${sourceFileName || "External Theme"}
   {% endcomment %}

Return ONLY a JSON object:
- "targetFileName": string (formatted like "es-cloned-${(sourceFileName || 'section').replace(/[^a-z0-9]/gi, '-').toLowerCase()}.liquid")
- "liquidCode": string (the complete refactored Liquid code)
- "changesSummary": string[] (list of refactoring improvements made)
- "originalIssuesFound": string[] (deprecated tags, missing schema properties, etc.)`;

    const response = await ai.models.generateContent({
      model: "gemini-3.6-flash",
      contents: `Source File: ${sourceFileName}\n\nSource Code:\n${sourceLiquidCode}\n\nCustomization Notes: ${customizationNotes || "Clone and modernize for E-sellers Pro"}`,
      config: {
        systemInstruction,
        responseMimeType: "application/json",
      },
    });

    const resultText = response.text || "{}";
    const data = JSON.parse(resultText);
    res.json({ success: true, data });
  } catch (error: any) {
    console.error("Error in clone-refactor:", error);
    res.status(500).json({ success: false, error: error.message || "Failed to clone/refactor section" });
  }
});

// AI Theme Audit API: Analyze uploaded Liquid files or ZIP structure
app.post("/api/gemini/audit-theme", async (req, res) => {
  try {
    const { fileList, sampleCode } = req.body;

    const systemInstruction = `You are a Senior Shopify Storefront & Performance Auditor for E-sellers Pro themes.
Analyze the provided Shopify theme structure and Liquid snippets.

Return a JSON report:
- "performanceScore": number (0 to 100)
- "os2CompatibilityScore": number (0 to 100)
- "criticalIssues": string[]
- "deprecatedTagsFound": string[]
- "recommendations": string[]
- "clonableSections": string[] (sections that are great candidates to clone/migrate)
- "summary": string`;

    const response = await ai.models.generateContent({
      model: "gemini-3.6-flash",
      contents: `Theme Files:\n${JSON.stringify(fileList, null, 2)}\n\nSample Code Snippets for Analysis:\n${(sampleCode || []).join("\n---\n")}`,
      config: {
        systemInstruction,
        responseMimeType: "application/json",
      },
    });

    const resultText = response.text || "{}";
    const data = JSON.parse(resultText);
    res.json({ success: true, data });
  } catch (error: any) {
    console.error("Error in audit-theme:", error);
    res.status(500).json({ success: false, error: error.message || "Failed to audit theme" });
  }
});

async function startServer() {
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (_req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on http://0.0.0.0:${PORT}`);
  });
}

startServer();
